<a href="https://colab.research.google.com/github/europecodingschool/ECS---VB---YZ---08.26/blob/main/VB_YZ_Ders_11_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [25]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [26]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

In [27]:
df = pd.read_csv("/content/telekom_musteri.csv")

In [28]:
df.head() # datamız bir telekom şirketi müşteri datası. Hedefimiz müşterinin ayrılıp ayrılmayacağını tahmin edip ona göre marketing ve satış ekibine bilgi vermek.

,musteri_id,yas,kullanim_suresi_ay,sozlesme_tipi,internet_hizi_mbps,ek_paket_sayisi,aylik_ucret,teknik_destek_cagrisi,fatura_gecikme_sayisi,memnuniyet_puani,musteri_no_son_hane,ayrildi_mi
0,10001,48,12,Aylik,25,2,215.0,0,1,9,6,0
1,10002,40,18,Aylik,100,2,465.0,0,1,9,9,0
2,10003,50,3,Yillik,50,3,364.0,0,0,6,0,0
3,10004,62,24,Iki Yillik,50,1,247.0,1,0,7,5,0
4,10005,39,32,Yillik,25,2,224.0,1,1,6,0,0

In [29]:
df.shape

(2000, 12)

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   musteri_id             2000 non-null   int64
 1   yas                    2000 non-null   int64
 2   kullanim_suresi_ay     2000 non-null   int64
 3   sozlesme_tipi          2000 non-null   object
 4   internet_hizi_mbps     2000 non-null   int64
 5   ek_paket_sayisi        2000 non-null   int64
 6   aylik_ucret            2000 non-null   float64
 7   teknik_destek_cagrisi  2000 non-null   int64
 8   fatura_gecikme_sayisi  2000 non-null   int64
 9   memnuniyet_puani       2000 non-null   int64
 10  musteri_no_son_hane    2000 non-null   int64
 11  ayrildi_mi             2000 non-null   int64
dtypes: float64(1), int64(10), object(1)
memory usage: 187.6+ KB

In [31]:
df.isnull().sum()

musteri_id               0
yas                      0
kullanim_suresi_ay       0
sozlesme_tipi            0
internet_hizi_mbps       0
ek_paket_sayisi          0
aylik_ucret              0
teknik_destek_cagrisi    0
fatura_gecikme_sayisi    0
memnuniyet_puani         0
musteri_no_son_hane      0
ayrildi_mi               0
dtype: int64

In [32]:
df['ayrildi_mi'].value_counts() # 0 müşteri kaldı demek, 1 ayrıldı demek.

ayrildi_mi
0    1449
1     551
Name: count, dtype: int64

In [33]:
df['ayrildi_mi'].value_counts(normalize=True) # hedef değerimizin dağılımına bir bakıyoruz.

ayrildi_mi
0    0.7245
1    0.2755
Name: proportion, dtype: float64

In [34]:
veri_model = df.drop(columns=["musteri_id","musteri_no_son_hane"]) #öğrenme algoritmamıza etki etmeyeceğini düşündüğümüz sütunları çıkardık.

In [35]:
veri_model.head()

,yas,kullanim_suresi_ay,sozlesme_tipi,internet_hizi_mbps,ek_paket_sayisi,aylik_ucret,teknik_destek_cagrisi,fatura_gecikme_sayisi,memnuniyet_puani,ayrildi_mi
0,48,12,Aylik,25,2,215.0,0,1,9,0
1,40,18,Aylik,100,2,465.0,0,1,9,0
2,50,3,Yillik,50,3,364.0,0,0,6,0
3,62,24,Iki Yillik,50,1,247.0,1,0,7,0
4,39,32,Yillik,25,2,224.0,1,1,6,0

In [36]:
veri_model = pd.get_dummies(veri_model, columns=['sozlesme_tipi'],drop_first=True, dtype=int)

In [38]:
veri_model.head()

,yas,kullanim_suresi_ay,internet_hizi_mbps,ek_paket_sayisi,aylik_ucret,teknik_destek_cagrisi,fatura_gecikme_sayisi,memnuniyet_puani,ayrildi_mi,sozlesme_tipi_Iki Yillik,sozlesme_tipi_Yillik
0,48,12,25,2,215.0,0,1,9,0,0,0
1,40,18,100,2,465.0,0,1,9,0,0,0
2,50,3,50,3,364.0,0,0,6,0,0,1
3,62,24,50,1,247.0,1,0,7,0,1,0
4,39,32,25,2,224.0,1,1,6,0,0,1

In [39]:
veri_model.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 11 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   yas                       2000 non-null   int64
 1   kullanim_suresi_ay        2000 non-null   int64
 2   internet_hizi_mbps        2000 non-null   int64
 3   ek_paket_sayisi           2000 non-null   int64
 4   aylik_ucret               2000 non-null   float64
 5   teknik_destek_cagrisi     2000 non-null   int64
 6   fatura_gecikme_sayisi     2000 non-null   int64
 7   memnuniyet_puani          2000 non-null   int64
 8   ayrildi_mi                2000 non-null   int64
 9   sozlesme_tipi_Iki Yillik  2000 non-null   int64
 10  sozlesme_tipi_Yillik      2000 non-null   int64
dtypes: float64(1), int64(10)
memory usage: 172.0 KB