<a href="https://colab.research.google.com/github/europecodingschool/ECS---VB---YZ---08.26/blob/main/VB_YZ_Ders_5_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import numpy as np
import pandas as pd

**Series **

In [5]:
notlar = {"Gürhan": 50, "Ayşe": 60, "Leyla":70}

In [7]:
notlar

{'Gürhan': 50, 'Ayşe': 60, 'Leyla': 70}

In [10]:
pd.Series(notlar)

Gürhan    50
Ayşe      60
Leyla     70
dtype: int64

In [12]:
numpy_array = np.array([50,60,70,80])

In [15]:
numpy_array

array([50, 60, 70, 80])

In [16]:
pd.Series(numpy_array)

0    50
1    60
2    70
3    80
dtype: int64

**Data Frame**

In [18]:
data = np.random.randint(10, size=(4,4))

In [20]:
data

array([[6, 7, 1, 6],
       [6, 4, 0, 7],
       [0, 6, 1, 3],
       [5, 8, 9, 6]])

In [22]:
data_frame = pd.DataFrame(data)

In [24]:
data_frame

   0  1  2  3
0  6  7  1  6
1  6  4  0  7
2  0  6  1  3
3  5  8  9  6

In [26]:
type(data_frame)

pandas.core.frame.DataFrame

In [28]:
data_frame[0]

0    6
1    6
2    0
3    5
Name: 0, dtype: int64

In [30]:
type(data_frame[0])

pandas.core.series.Series

In [32]:
data_frame

   0  1  2  3
0  6  7  1  6
1  6  4  0  7
2  0  6  1  3
3  5  8  9  6

In [34]:
new_df = pd.DataFrame(data, index=["Gürhan","Ayşe","Elif","Melike"], columns = ["Ders1","Ders2", "Ders3","Ders4"])

In [36]:
new_df

        Ders1  Ders2  Ders3  Ders4
Gürhan      6      7      1      6
Ayşe        6      4      0      7
Elif        0      6      1      3
Melike      5      8      9      6

In [38]:
new_df['Ders1']

Gürhan    6
Ayşe      6
Elif      0
Melike    5
Name: Ders1, dtype: int64

In [40]:
new_df['Ders2']

Gürhan    7
Ayşe      4
Elif      6
Melike    8
Name: Ders2, dtype: int64

In [42]:
new_df['Ders3']

Gürhan    1
Ayşe      0
Elif      1
Melike    9
Name: Ders3, dtype: int64

In [45]:
# new_df['Gürhan']. - satır seçerken hata verir.

In [47]:
new_df.loc["Gürhan"]

Ders1    6
Ders2    7
Ders3    1
Ders4    6
Name: Gürhan, dtype: int64

In [49]:
new_df.loc["Elif"]

Ders1    0
Ders2    6
Ders3    1
Ders4    3
Name: Elif, dtype: int64

In [52]:
new_df.iloc[0]

Ders1    6
Ders2    7
Ders3    1
Ders4    6
Name: Gürhan, dtype: int64

In [54]:
new_df.iloc[1]

Ders1    6
Ders2    4
Ders3    0
Ders4    7
Name: Ayşe, dtype: int64

In [56]:
new_df.iloc[3]

Ders1    5
Ders2    8
Ders3    9
Ders4    6
Name: Melike, dtype: int64

In [58]:
new_df.loc[["Ayşe","Elif"]]

      Ders1  Ders2  Ders3  Ders4
Ayşe      6      4      0      7
Elif      0      6      1      3

In [60]:
new_df.loc["Gürhan":"Elif"]

        Ders1  Ders2  Ders3  Ders4
Gürhan      6      7      1      6
Ayşe        6      4      0      7
Elif        0      6      1      3

In [62]:
new_df.iloc[0:2]

        Ders1  Ders2  Ders3  Ders4
Gürhan      6      7      1      6
Ayşe        6      4      0      7

In [64]:
new_df.iloc[0:3]

        Ders1  Ders2  Ders3  Ders4
Gürhan      6      7      1      6
Ayşe        6      4      0      7
Elif        0      6      1      3

In [65]:
new_df.iloc[0:3,1:3] -

        Ders2  Ders3
Gürhan      7      1
Ayşe        4      0
Elif        6      1